import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import tableStyles from '../../styles/Table.module.css'
import ToDoList from '../../components/ToDoList'
import { gql, useQuery } from '@apollo/client'
import { client } from '../_app'
import { useEffect, useState } from 'react'

// data schema
// {
//   id: number;
//   text: string;
//   completed: boolean;
//   createdAt: Date
// }

const GET_TODOS = gql`
{
  todos {
    id,
    text,
    completed,
    createdAt
  }
}
`

const Index = () => {
  const { data, loading, error, refetch, networkStatus } = useQuery(GET_TODOS, { fetchPolicy: "no-cache" })
  const [allToDos, setAllToDos] = useState([])
  
  useEffect(() => {
    async function getData() {
      const { data } = await refetch()
      setAllToDos(data.todos)
    }
    getData()
  }, [])
  
  return (
    <div className={styles.container}>
      <Head>
        <title>To-Do Web App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Here's your to-do list!</h1>
        <div className={tableStyles.content}>
          <ToDoList data={allToDos}/>
        </div>
      </main>
    </div>
  );
}

export default Index;