import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>To-Do Web App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>To-Do Web App</h1>
        <p><Link href='/todos'><a>Click here</a></Link> to go to the to-do list.</p>
      </main>
    </div>
  )
}

export default Home
